/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.*;
import service.*;
import exception.*;
import interfaces.MetodePembayaran;
import util.JsonUtil;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TransaksiKasirUI extends javax.swing.JFrame {
    
    private StokService stokGudang;
    private KasirService mesinKasir;
    private List<Pelanggan> daftarPelanggan;
    private Pelanggan pelangganAktif;
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransaksiKasirUI.class.getName());

    /**
     * Creates new form TransaksiKasirUI
     */
    public TransaksiKasirUI() {
        initComponents();
        
        this.stokGudang = new StokService();
        this.mesinKasir = new KasirService();
        this.mesinKasir.setDiskonStrategi(new DiskonMemberService());
        this.daftarPelanggan = JsonUtil.bacaDariJson("data/pelanggan.json", new TypeToken<List<Pelanggan>>(){}.getType());
        this.tableModel = (DefaultTableModel) tblKeranjang.getModel();
        this.tableModel.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamaPelanggan = new javax.swing.JTextField();
        txtNamaProduk = new javax.swing.JTextField();
        txtJumlahBeli = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        lblTotalTagihan = new javax.swing.JLabel();
        cmbMetodeBayar = new javax.swing.JComboBox<>();
        txtUangBayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNamaPelanggan.addActionListener(this::txtNamaPelangganActionPerformed);

        txtNamaProduk.addActionListener(this::txtNamaProdukActionPerformed);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        lblTotalTagihan.setText("Total Tagihan: Rp 0");

        cmbMetodeBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "EWallet", "Kartu" }));
        cmbMetodeBayar.addActionListener(this::cmbMetodeBayarActionPerformed);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMetodeBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBayar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTotalTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalTagihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMetodeBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar))
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPelangganActionPerformed

    private void cmbMetodeBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodeBayarActionPerformed
        
    }//GEN-LAST:event_cmbMetodeBayarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
                                                                           
        try {
            // Ambil text input dari textfield di GUI
            String namaPelanggan = txtNamaPelanggan.getText().trim();
            String namaBarangInput = txtNamaProduk.getText().trim(); 
            int jumlah = Integer.parseInt(txtJumlahBeli.getText().trim());

            // Validasi input kosong
            if (namaPelanggan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Pelanggan tidak boleh kosong!");
                return;
            }
            if (namaBarangInput.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama/Merk Produk tidak boleh kosong!");
                return;
            }

            // 1. Logika Cari atau Set Pelanggan Berdasarkan Nama
            if (pelangganAktif == null || !pelangganAktif.getNama().equalsIgnoreCase(namaPelanggan)) {
                pelangganAktif = null;
                for (Pelanggan p : daftarPelanggan) {
                    if (p.getNama().equalsIgnoreCase(namaPelanggan)) {
                        pelangganAktif = p;
                        break;
                    }
                }
                // Jika nama pelanggan tidak terdaftar di JSON, otomatis buat member VIP baru untuk simulasi
                if (pelangganAktif == null) {
                    pelangganAktif = new Pelanggan("M-" + System.currentTimeMillis() % 1000, namaPelanggan, "VIP");
                    daftarPelanggan.add(pelangganAktif);
                }
                mesinKasir.setPelanggan(pelangganAktif);
            }

            // 2. Logika Mencari Produk Berdasarkan Nama/Merk di dalam data produk JSON
            Produk produkDitemukan = null;
            for (Produk prod : stokGudang.getDaftarProduk()) {
                if (prod.getNama().toLowerCase().contains(namaBarangInput.toLowerCase())) {
                    produkDitemukan = prod;
                    break;
                }
            }

            if (produkDitemukan == null) {
                JOptionPane.showMessageDialog(this, "Produk dengan merk '" + namaBarangInput + "' tidak ditemukan di database JSON!");
                return;
            }

            // 3. Validasi stok di backend menggunakan ID asli produk yang ketemu
            stokGudang.validasiStokBarang(produkDitemukan.getIdProduk(), jumlah);
            mesinKasir.tambahKeKeranjang(produkDitemukan, jumlah);

            // 4. Masukkan data belanja ke baris JTable visual (Format Harga double tetap dibiarkan di tabel)
            double subtotal = produkDitemukan.getHarga() * jumlah;
            tableModel.addRow(new Object[]{
                produkDitemukan.getIdProduk(), 
                produkDitemukan.getNama(), 
                produkDitemukan.getHarga(), 
                jumlah, 
                subtotal
            });

            // 5. Update teks total tagihan di layar GUI (Dipaksa cast ke (int) biar ga ada .0 di belakangnya)
            lblTotalTagihan.setText("Total Tagihan: Rp " + (int) mesinKasir.hitungTotalTagihan());
            
            // Bersihkan input teks barang biar bisa ketik barang selanjutnya
            txtNamaProduk.setText("");
            txtJumlahBeli.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah beli harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProdukActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
                                       
        try {
            // Validasi apakah sudah klik tombol tambah atau belum sebelum bayar
            if (pelangganAktif == null) {
                JOptionPane.showMessageDialog(this, "Belum ada transaksi yang diproses! Isi data & klik Tambah dulu.");
                return;
            }

            double uangDibayar = Double.parseDouble(txtUangBayar.getText().trim());
            String opsiMetode = cmbMetodeBayar.getSelectedItem().toString();

            // Menentukan instansiasi objek Polymorphism dari strategi Metode Pembayaran
            interfaces.MetodePembayaran metode;
            if (opsiMetode.equalsIgnoreCase("EWallet")) {
                metode = new service.PembayaranEWallet();
            } else if (opsiMetode.equalsIgnoreCase("Kartu")) {
                metode = new service.PembayaranKartu();
            } else {
                metode = new service.PembayaranTunai();
            }

            // Eksekusi bayar di mesin kasir backend
            mesinKasir.selesaikanTransaksi(metode, uangDibayar);

            // --- JALUR ABSOLUT: MEMAKSA SIMPAN PERUBAHAN LANGSUNG KE FILE FISIK WINDOWS ---
            stokGudang.simpanPerubahan(); // Update stok berkurang di produk.json
            util.JsonUtil.simpanKeJson("D:/KasirCerdasGUI/data/pelanggan.json", daftarPelanggan); // Update poin baru pelanggan

            // Tampilkan pop up bukti transaksi sukses
            JOptionPane.showMessageDialog(this, "TRANSAKSI SUKSES!\nFile Database JSON sukses diperbarui.\nPoin Member " 
                    + pelangganAktif.getNama() + " Sekarang: " + pelangganAktif.getPoin() + " Poin");

            // --- RESET OTOMATIS LAYAR GUI SETELAH SUKSES BAYAR ---
            tableModel.setRowCount(0); // Keranjang belanja di tabel otomatis kosong kembali
            lblTotalTagihan.setText("Total Tagihan: Rp 0"); // Label kembali ke 0
            txtUangBayar.setText(""); // Kotak uang bayar bersih
            txtNamaPelanggan.setText(""); // Kotak nama pelanggan bersih
            pelangganAktif = null; // Reset session transaksi

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nominal uang pembayaran harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Transaksi Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransaksiKasirUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbMetodeBayar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalTagihan;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtJumlahBeli;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
}
